CREATE DATABASE IF NOT EXISTS mj_game DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS mj_log DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mj_game;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(64) NOT NULL,
  password_hash VARCHAR(128) DEFAULT NULL,
  device_id VARCHAR(128) DEFAULT NULL,
  head_img VARCHAR(256) DEFAULT '',
  sex TINYINT DEFAULT 1,
  room_card INT NOT NULL DEFAULT 9999,
  diamond INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_name (user_name),
  KEY idx_device (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  room_id INT NOT NULL,
  game_id VARCHAR(32) NOT NULL,
  round_no INT NOT NULL DEFAULT 1,
  winner_seat INT DEFAULT NULL,
  reason VARCHAR(32) DEFAULT NULL,
  detail TEXT,
  scores_json JSON,
  birds_json JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_room (room_id),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game_record_players (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  record_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  seat INT NOT NULL,
  score_delta INT NOT NULL DEFAULT 0,
  KEY idx_record (record_id),
  KEY idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS room_card_ledger (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  delta INT NOT NULL,
  balance INT NOT NULL,
  reason VARCHAR(64) NOT NULL,
  ref_id VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clubs (
  club_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  club_name VARCHAR(64) NOT NULL,
  owner_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS club_members (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  club_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'member',
  UNIQUE KEY uk_club_user (club_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 兼容旧表名（若已有 t_user 可忽略）
CREATE TABLE IF NOT EXISTS t_user (
  user_id INT PRIMARY KEY,
  user_name VARCHAR(64),
  room_card INT DEFAULT 9999,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
