CREATE DATABASE IF NOT EXISTS mj_game DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS mj_log DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS mj_log_template DEFAULT CHARACTER SET utf8mb4;

USE mj_game;
CREATE TABLE IF NOT EXISTS t_user (
  user_id INT PRIMARY KEY,
  user_name VARCHAR(64),
  room_card INT DEFAULT 9999,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS t_club (
  club_id INT PRIMARY KEY,
  club_name VARCHAR(64),
  owner_id INT
);
